name: CI/CD Backend

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ---- Build & Push image vers GHCR ----
      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push image
        run: |
          set -euo pipefail
          OWNER_LC=$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')
          IMAGE="ghcr.io/${OWNER_LC}/slapit-backend"
          echo "Building $IMAGE:latest"
          docker build -t "$IMAGE:latest" ./backend
          docker push "$IMAGE:latest"

      # ---- Déploiement: sync fichiers vers le VPS (pas de known_hosts) ----
      - name: Sync repo to VPS (rsync)
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -az --delete --exclude '.git' --exclude '.github'
          path: ./
          remote_path: /home/${{ secrets.VPS_USER }}/apps/slapit
          remote_host: ${{ secrets.VPS_HOST }}
          remote_user: ${{ secrets.VPS_USER }}
          remote_key: ${{ secrets.VPS_SSH_KEY }}
          rsh: 'ssh -o StrictHostKeyChecking=no'

      # ---- Compose pull & up sur le VPS (retries inclus) ----
      - name: Compose pull & up
        uses: appleboy/ssh-action@v1.2.0
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          envs: SUPABASE_URL,SUPABASE_KEY
          script: |
            set -euo pipefail
            APP_DIR="/home/${{ secrets.VPS_USER }}/apps/slapit"
            cd "$APP_DIR"

            # Forcer l'image GHCR (owner en minuscules)
            OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
            sed -i "s|image: .*slapit-backend.*|image: ghcr.io/${OWNER_LC}/slapit-backend:latest|g" docker-compose.yml || true

            # (Ré)écrire backend/.env depuis les secrets
            mkdir -p backend
            {
              echo "SUPABASE_URL=${SUPABASE_URL}"
              echo "SUPABASE_KEY=${SUPABASE_KEY}"
              echo "ENV=production"
            } > backend/.env

            # Petite fonction retry pour les pulls (DNS / réseau parfois flaky)
            retry() { n=0; until [ $n -ge 6 ]; do "$@" && break; n=$((n+1)); echo "retry $n..."; sleep 6; done; }

            # Pull & up
            retry docker compose pull
            docker compose up -d --remove-orphans

            # Nettoyage léger
            docker system prune -f
