name: CI/CD

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Owner (lowercase)
        id: vars
        run: echo "owner_lc=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT

      # 1) LOGIN GHCR AVANT DE BUILDER/PUSHER
      - name: Login to GHCR (for push)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 2) BUILD + PUSH
      - name: Build & Push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: ghcr.io/${{ steps.vars.outputs.owner_lc }}/slapit-backend:latest
          provenance: false

      # 3) UPLOAD DU CODE SUR LE VPS
      - name: Upload repo to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 2222
          source: .
          target: /home/${{ secrets.VPS_USER }}/apps/slapit
          overwrite: true
          timeout: 60s
          command_timeout: 10m

      # 4) DEPLOY SUR LE VPS
      - name: Deploy on VPS
        uses: appleboy/ssh-action@v1.2.0
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          GHCR_PAT: ${{ secrets.GHCR_PAT }}   # <-- PAT perso (write:packages)
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 2222
          timeout: 120s
          command_timeout: 15m
          script_stop: true
          script: |
            set -euo pipefail
            APP_DIR="/home/${{ secrets.VPS_USER }}/apps/slapit"
            cd "$APP_DIR"

            # Forcer l’image en latest (owner en minuscules)
            OWNER_LC="$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')"
            sed -i "s|image: .*slapit-backend.*|image: ghcr.io/${OWNER_LC}/slapit-backend:latest|g" docker-compose.yml || true

            # .env backend
            mkdir -p backend
            {
              echo "SUPABASE_URL=${SUPABASE_URL}"
              echo "SUPABASE_KEY=${SUPABASE_KEY}"
              echo "ENV=production"
            } > backend/.env

            # LOGIN GHCR côté VPS avec PAT (PAS le GITHUB_TOKEN)
            echo "${GHCR_PAT}" | docker login ghcr.io -u "${{ steps.vars.outputs.owner_lc }}" --password-stdin

            docker compose pull
            docker compose up -d --remove-orphans
            docker system prune -f
