name: CI/CD Backend

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Build & Push vers GHCR (owner/repo en minuscules)
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Docker image
        run: |
          IMAGE=ghcr.io/${{ toLower(github.repository_owner) }}/${{ toLower(github.event.repository.name) }}/slapit-backend
          echo "Using image: $IMAGE:latest"
          docker build -t $IMAGE:latest ./backend
          docker push $IMAGE:latest

      # Déploiement sur VPS
      - name: Deploy on VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e
            cd ~/apps/slapit

            if [ ! -d .git ]; then
              git clone https://github.com/${{ github.repository }} .
            else
              git fetch origin main && git reset --hard origin/main
            fi

            # Remplace l'image dans docker-compose si besoin
            IMAGE="ghcr.io/${{ toLower(github.repository_owner) }}/${{ toLower(github.event.repository.name) }}/slapit-backend:latest"
            sed -i "s|image: .*slapit-backend.*|image: ${IMAGE}|g" docker-compose.yml || true

            docker compose pull
            docker compose up -d --remove-orphans
            docker system prune -f
