name: CI/CD Backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 🔹 Build & Push l'image sur GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Docker image
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner,, }}/slapit/slapit-backend
          docker build -t $IMAGE:latest ./backend
          docker push $IMAGE:latest

      # 🔹 Déploiement sur VPS via SSH
      - name: Deploy on VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e
            cd ~/apps/slapit

            # pull repo + maj
            if [ ! -d .git ]; then
              git clone https://github.com/${{ github.repository }} .
            else
              git fetch origin main && git reset --hard origin/main
            fi

            # update images & restart
            docker compose pull
            docker compose up -d --remove-orphans

            docker system prune -f
